#  application.yaml работает в jvm и native, но не работает в режиме сервлета с Tomcat
# в этом случае необходимо сформировать application.conf

ktor:
  deployment:
    port: 8080
  watch:
    - classes
    - resources
  application:
    modules:
      - "AppKt.moduleJvm"
  urls:
    - "http://127.0.0.1:8080/"
    - "http://0.0.0.0:8080/"
    - "http://192.168.0.182:8080/"
adsCar:
  repository:
    test: inmemory
    prod: inmemory
#    prod: cassandra
    cassandra:
      host: localhost
      keyspace: test_keyspace
      pass: cassandra
      port: 9042
      user: cassandra
      testing: true
