#  application.yaml работает в jvm и native, но не работает в режиме сервлета с Tomcat
# в этом случае необходимо сформировать application.conf

ktor:
  deployment:
    port: 8080
  watch:
    - classes
    - resources
  application:
    modules:
      - "AppKt.moduleJvm"
  urls:
    - "http://127.0.0.1:8080/"
    - "http://0.0.0.0:8080/"
    - "http://192.168.0.182:8080/"
adsCar:
  repository:
    test: "$DB_TEST:inmemory"
    prod: "$DB_PROD:inmemory"
    cassandra:
      host: "$CS_HOST:localhost"
      port: "$CS_PORT:9042"
      keyspace: "$CS_KEYSPACE:test_keyspace"
      pass: "$CS_USER:cassandra"
      user: "$CS_USER:cassandra"
      testing: "$CS_TESTING:false"
  jwt:
    secret: "secret"
    issuer: "OtusKotlin"
    audience: "ad-users"
    realm: "ads"
    clientId: "otus-ads-service"
