openapi: 3.0.4
info:
  title: AdsCar
  description: "This is a place where sellers and buyers cars"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: adCar
    description: "Объявление (о покупке или продаже) автомобиля"
paths:
  /v1/ad/create:
    post:
      tags:
        - adCar
      summary: Create AdCar
      operationId: adCarCreate
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdCreateRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdCreateResponse'
  /v1/ad/read:
    post:
      tags:
        - adCar
      summary: Read AdCar
      operationId: adCarRead
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdReadRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdReadResponse'
  /v1/ad/update:
    post:
      tags:
        - adCar
      summary: Update AdCar
      operationId: adCarUpdate
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdUpdateRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdUpdateResponse'
  /v1/ad/delete:
    post:
      tags:
        - adCar
      summary: Update AdCar
      operationId: adCarDelete
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdDeleteRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdDeleteResponse'

  /v1/ad/search:
    post:
      tags:
        - adCar
      summary: Update AdCar
      operationId: adCarSearch
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdSearchRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdSearchResponse'
components:
  schemas:
    # Запросы
    IRequest:
      type: object
      description: "Базовый интерфейс для всех запросов"
      properties:
        requestType:
          type: string
          description: "Поле-дескриминатор для вычисления типа запроса"
          example: create
        requestId:
          type: string
          description: "Идентификатор запроса для отладки"
      discriminator:
        propertyName: requestType
        mapping:
          create: '#/components/schemas/AdCreateRequest'
          read: '#/components/schemas/AdReadRequest'
          update: '#/components/schemas/AdUpdateRequest'
          delete: '#/components/schemas/AdDeleteRequest'
          search: '#/components/schemas/AdSearchRequest'

    AdCreateRequest:
      description: "Запрос создания объявления"
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            debug:
              $ref: '#/components/schemas/AdRequestDebug'
        - type: object
          description: "Сущность создания объявления"
          properties:
            adCreate:
              $ref: "#/components/schemas/AdCreateOrUpdateObject"

    AdReadRequest:
      description: "Запрос на чтение одного объявления"
      allOf:
        - $ref: "#/components/schemas/IRequest"
        - type: object
          description: "Дебаг"
          properties:
            debug:
              $ref: "#/components/schemas/AdRequestDebug"
        - type: object
          description: "Сущность чтения объявления"
          properties:
            adRead:
              $ref: "#/components/schemas/AdReadObject"

    AdReadObject:
      description: "Сущность чтения объявления"
      properties:
        id:
          $ref: "#/components/schemas/AdId"

    AdUpdateRequest:
      description: "Запрос на обновление объявления"
      allOf:
        - $ref: "#/components/schemas/IRequest"
        - type: object
          description: "Дебаг"
          properties:
            debug:
              $ref: "#/components/schemas/AdRequestDebug"
        - type: object
          description: "Сущность обновления объявления"
          properties:
            adUpdate:
              $ref: "#/components/schemas/AdCreateOrUpdateObject"

    AdCreateOrUpdateObject:
      description: "Сущность создания/обновления объявления"
      allOf:
        - $ref: "#/components/schemas/BaseAd"

    AdDeleteRequest:
      description: "Запрос на удаление объявления"
      allOf:
        - $ref: "#/components/schemas/IRequest"
        - type: object
          description: "Дебаг"
          properties:
            debug:
              $ref: "#/components/schemas/AdRequestDebug"
        - type: object
          description: "Сущность удаления объявления"
          properties:
            adDelete:
              $ref: "#/components/schemas/AdDeleteObject"

    AdDeleteObject:
      description: "Сущность удаления объявления"
      type: object
      properties:
        id:
          $ref: "#/components/schemas/AdId"
        lock:
          $ref: "#/components/schemas/AdLock"

    AdSearchRequest:
      description: "Запрос на поиск объявлений"
      allOf:
        - $ref: "#/components/schemas/IRequest"
        - type: object
          description: "Дебаг"
          properties:
            debug:
              $ref: "#/components/schemas/AdRequestDebug"
        - type: object
          description: "Набор фильтров для поиска"
          properties:
            adFilter:
              $ref: "#/components/schemas/AdSearchFilter"

    # Ответы
    IResponse:
      type: object
      description: "Базовый интерфейс для всех ответов"
      properties:
        responseType:
          type: string
          description: "Поле-дескриминатор для вычисления типа запроса"
          example: create
        requestId:
          type: string
          description: "Идентификатор запроса для отладки"
        result:
          $ref: '#/components/schemas/ResponseResult'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'

      discriminator:
        propertyName: responseType
        mapping:
          create: '#/components/schemas/AdCreateResponse'
          read: '#/components/schemas/AdReadResponse'
          update: '#/components/schemas/AdUpdateResponse'
          delete: '#/components/schemas/AdDeleteResponse'
          search: '#/components/schemas/AdSearchResponse'
          init: '#/components/schemas/AdInitResponse'

    AdCreateResponse:
      description: "Ответ на запрос создания объявления"
      allOf:
        - $ref: "#/components/schemas/IResponse"
        - $ref: "#/components/schemas/AdResponseSingle"

    AdReadResponse:
      description: "Ответ на запрос чтения объявления"
      allOf:
        - $ref: "#/components/schemas/IResponse"
        - $ref: "#/components/schemas/AdResponseSingle"

    AdUpdateResponse:
      description: "Ответ на запрос обновления объявления"
      allOf:
        - $ref: "#/components/schemas/IResponse"
        - $ref: "#/components/schemas/AdResponseSingle"

    AdDeleteResponse:
      description: "Ответ на запрос удаления объявления"
      allOf:
        - $ref: "#/components/schemas/IResponse"
        - $ref: "#/components/schemas/AdResponseSingle"

    AdSearchResponse:
      description: "Ответ на запрос поиска объявлений"
      allOf:
        - $ref: "#/components/schemas/IResponse"
        - $ref: "#/components/schemas/AdResponseMulti"

    AdResponseSingle:
      description: "Ответ с одним объектом объявления"
      type: object
      properties:
        ad:
          $ref: "#/components/schemas/AdResponseObject"

    AdResponseMulti:
      type: object
      description: "Список найденных объектов"
      properties:
        ads:
          type: array
          items:
            $ref: "#/components/schemas/AdResponseObject"

    AdResponseObject:
      allOf:
        - $ref: '#/components/schemas/BaseAd'
        - type: object
          description: "Объект ответа бэкенда"
          properties:
            id:
              $ref: "#/components/schemas/AdId"
            ownerId:
              $ref: "#/components/schemas/UserId"
            lock:
              $ref: "#/components/schemas/AdLock"
            permissions:
              type: array
              uniqueItems: true
              items:
                $ref: "#/components/schemas/AdPermissions"

    # Сущности
    BaseAd:
      type: object
      description: "Базовая сущность объявления"
      properties:
        title:
          type: string
          description: 'Заголовок объявления'
        description:
          type: string
          description: 'Описание объявления'
        visibility:
          $ref: '#/components/schemas/AdVisibility'
        logos:
          type: array
          items:
            type: string
          description: "Фото автомобиля"
        ownerId:
          type: string
          description: "Владелец автомобиля"
        price:
          type: number
          description: "Цена автомобиля"

    AdSearchFilter:
      type: object
      description: "Набор фильтров для поиска"
      properties:
        searchString:
          type: string
          description: "Поисковая строка, которая будет искаться в объявлениях"

    AdVisibility:
      type: string
      description: 'Видимость объявления'
      enum:
        - ownerOnly
        - registeredOnly
        - public

    AdPermissions:
      type: string
      description: "Доступы для клиента для операций над объявлением"
      enum:
        - read
        - update
        - delete
        - makeVisiblePublic
        - makeVisibleOwn
        - makeVisibleGroup

    Error:
      description: "Сущность ошибки"
      type: object
      properties:
        code:
          type: string
        group:
          type: string
        field:
          type: string
        message:
          type: string

    ResponseResult:
      description: "Результат ответа"
      enum:
        - error
        - success

    AdId:
      type: string
      description: "Идентификатор объявления"

    AdLock:
      type: string
      description: "Версия оптимистичной блокировки(Вообще не понятно что это)"

    UserId:
      type: string
      description: "Идентификатор пользователя"

    AdInitResponse:
      allOf:
        - $ref: "#/components/schemas/IResponse"

    # STUBS ======================

    AdRequestDebug:
      type: object
      description: "Это запрос в режиме дебага?"
      properties:
        mode:
          $ref: "#/components/schemas/AdRequestDebugMode"
        stub:
          $ref: "#/components/schemas/AdRequestDebugStubs"

    AdRequestDebugMode:
      type: string
      enum:
        - prod
        - test
        - stub

    AdRequestDebugStubs:
      type: string
      description: "Перечисления всех стабов"
      enum:
        - success
        - notFound
        - badId
        - badTitle
        - badDescription
        - badVisibility
        - cannotDelete
        - badSearchString